---

  # copies a backup of your openbazaar store to the local machine

- hosts: sab
  remote_user: root

  vars_files:
    - vars/secret.yml
    - vars/public.yml

  tasks:
    - name: stop the openbazaar server for maintenance
      service: name=openbazaard state=stopped

    - name: get timestamp
      set_fact:
        timestamp: "{{ ansible_date_time.iso8601 }}"

    - name: backup the .openbazaar folder
      shell: "tar cvzf /tmp/openbazaar-backup_{{ timestamp }}.tar.gz .openbazaar"
      args:
        chdir: "{{openbazaar_user_home_directory}}/"
        creates: "/tmp/openbazaar-backup_{{ timestamp }}.tar.gz"

    - name: copy backup to local machine
      fetch: src="/tmp/openbazaar-backup_{{timestamp}}.tar.gz" dest="{{archive_directory}}"

    - name: restart the openbazaar server
      service: name=openbazaard state=started
