---

  # restores a local backup to the remote machine.

- hosts: nuqik2
  remote_user: root

  vars_files:
    - vars/secret.yml
    - vars/public.yml


  tasks:
    - name: get past archives
      delegate_to: localhost
      find: paths="{{archive_directory}}/{{ ansible_hostname }}/tmp"
      register: past_archives

    - debug: msg="{{past_archives}}"
    - debug: msg="{{past_archives.files[-1].path}}"

    - name: get timestamp
      set_fact:
        timestamp: "{{ ansible_date_time.iso8601 }}"

    - name: stop openbazaar server
      service: name=openbazaard state=stopped

    - name: delete any existing .openbazaar folder
      command: "mv /home/{{openbazaar_user}}/.openbazaar /home/{{openbazaar_user}}/.openbazaar.{{timestamp}}.bak"
      ignore_errors: True

    - name: upload & extract the archive
      unarchive: copy=yes src={{ past_archives.files[-1].path }} dest=/home/{{ openbazaar_user }}/

    - name: restart the openbazaar server
      service: name=openbazaard state=started