---

  # restores a local backup to the remote machine.

- hosts: sab
  remote_user: root

  vars_files:
    - vars/secret.yml
    - vars/public.yml


  tasks:
    - name: get past archives
      delegate_to: localhost
      find: paths={{archive_directory}}/{{ ansible_hostname }}/tmp/ patterns="ob_*.tar.gz"
      register: past_archives

    #- debug: msg={{past_archives}}

    - name: upload the latest archive
      copy: src={{ past_archives.files[0].path }} dest=/tmp/

    - name: upload and extract the archive
      unarchive: copy=yes src={{ past_archives.files[0].path }} dest=/home/{{ openbazaar_user }}/
